### PR TITLE
Added an option to select files with specific extensions

### PR DESCRIPTION
**Pull request by jans-johnson**
There was a drawback in the program that the directory should only contain the video files and nothing else and also the file format should only be mp4. I have resolved that issue.

### CODE REVIEW

**Review by lyraxvincent — CHANGES_REQUESTED** [review]
Thanks Johnson for your contribution.
The script however does not work for filenames with more than one "." (brings issues with the split(".") function. That seems to be solved by indexing the returned result with [-1] instead of [1] (same case in the write_audiofile() function)
Also the comment on line 6 I think should be "# Enter video formats" not audio formats. And to include all supported video formats. [link](https://zulko.github.io/moviepy/getting_started/videoclips.html)

**Comment by jans-johnson** [comment]
Sure

**Comment by jans-johnson** [comment]
I'm Pretty Sure that moviepy supports almost all the video formats. I assumed like the users will enter the video formats which they are going to use, before executing the program. I've commited the other changes which were requested.

**Review by lyraxvincent — APPROVED** [review]
Added some few changes, now merging.

**Pull request merged**
